kind: pipeline
name: build standalone app

steps:
  - name: build
    image: node:10.16.0-stretch
    environment:
      PUBLIC_URL: http://10.1.120.10:3000/thomas/ota-hello-expo/raw/master
    volumes:
      - name: dist
        path: /tmp
    commands:
      # - yarn
      # - yarn global add expo-cli
      # - expo optimize
      # - expo export -p $PUBLIC_URL
      # - cp -r dist /tmp
      - echo $(date) > test.json
      - cp test.json /tmp

  # - name: publish
  #   image: docker:git
  #   volumes:
  #     - name: dist
  #       path: /tmp
  #   environment:
  #     OTA_HOST: 10.1.120.10:3000
  #     OTA_ACCOUNT: thomas
  #     OTA_TOKEN: c3bf9b25e7d2fc44076535e9642819c0bf3d3ade
  #     OTA_REPO: thomas/ota-hello-expo
  #     USER_NAME: "Thomas Lin"
  #     USER_EMALI: thomas@hello.expo
  #   commands:
  #     - git config --global user.email "$USER_EMAIL"
  #     - git config --global user.name "$USER_NAME"
  #     - git init temp && cd temp
  #     - git remote add origin http://$OTA_ACCOUNT:$OTA_TOKEN@$OTA_HOST/$OTA_REPO
  #     - git pull --rebase origin master
  #     - cp /tmp/* ./
  #     - git add * && git commit -m "publish ota"
  #     - git push origin master

  - name: build standalone app
    image: node:10.16.0-alpine
    volumes:
      - name: output
        path: /tmp
    environment:
      # get from
      TURTLE_VERSION: 0.8.7
      ANDROID_KEYSTORE_BASE64: "/u3+7QAAAAIAAAABAAAAAQAKdGhvbWFzLWxpbgAAAWvZ2k+sAAAFATCCBP0wDgYKKwYBBAEqAhEBAQUABIIE6dugAOsx1wdwA+Uvcb7xa5L6p5wZNooCwL16XX0AIRsYlJg5G/34F5/pfnEr0k6dRbDVHlCe/x/0CgXhprNy8nibtYG3/fWiNEGJ09JM5+MhLHXyw15NSFLVlq2W1+5uALusnnVyHvR6F9MBHfpZZALGsInwLiQZVKVxclbQfz5hLoHII2f0MeATtwdsMmIjN3pWNFPLROWHNOU/p4oP2T7G7JPezWk0PAmmTJeH6dW2PFojjM2NzKfc4Gi4iFvxyWn5ztAzk49KHJRq4f1GdHlIoSkncuxNZlxTN9fWFIwO2FJazQDlfYldTtx92KfxB1/S/SIszCG1x9lRjNwydrIXMN17JqDBfqU2acBRjxI7XAOQITQXEB3PnbYVyIE84vGl/aXbmOp7q8oS3aIpDbQTIWawGuWo/qytaNhyeBvwYK/wOhaUirg6p0NGwtGUn72miOe8imlvElx5LiLz+ulFcvFtaUiB+6apaDpaqwzWt7L+GjygYE1KEmhExwE00ufZpQdeUY9dRsoxwqY0Z/GXWX8DI3JmRDeS5SUYHHIfsgXW/K/kd6H+LrchZAKbugsCI7MjKu4g7MdqEArHBP/6qVy3h1QO8tLguh46hkQi+ZxuCU86iCCkjygHRezaBk773Eyhc/R1sAVJqlf/BPFv124MNfkRyA7pM+m98T4PjCEHKoRnzhauR9LFK5piJW4/HNZtOS+lBjNnlsG8cWGJWWh+Tz0YfRxPKH2Yh8Mr9d+p8wanNsXgbXpyl/qVZXAnZbxmTPy3k9wFElanLZqiMSwb9hc7Gmdzk75LhqEMr/tg4ST2pHEh+yqW4aGPr+/pMlI8Nt5V3TOvWkBPROGPiYCbSla2qNXWgem7oZLuknrhVUgf2jeXe0Uj2NSgTzqTZbXYC3oAVzSe+I4squwSwNRF6utwqc2qc0Yy1BocsHA6cV4Yj792dxLEYGYYYvLV6T955EN4lwqHxn+rNnw/izgGebJg01sRHBi+jzQOuwZI8r/KuR8lDI/5PGzIbjep/mx73m/rv0o5JxBt2xQgGaLUTcc+3EA7/3MFmA5bGEGQRrpHMh99wkeIdTmPfADA5Vef4shK8cUMLtXyQruwEGfG9/7RcgRSHPgXZLCJZWJ6xY441wVo03NSxu0RUOvD46wAdZhCvdD4Mw2OJjZ6b5cbnoIbVhEErAPrFPCtlmyKkhSG36UdwpRxgG+Gmn6fRLMhK1quoI8P3jQ7RbrZ+1sUOmnL11SMlAKkMxPYrUIWCAmyEejOcpertbT7OR6fKfycILRp0pXiKH1qTw/7kQN20uoIN+PggZshEAaB8cptBaMVtekQUBV2TA+OnaM0/3UB1nlMAMxF2wKHbihYp5sm3C9NppsWPs2lfPEAtirbsOhE+3EfuOz8KpWnREtIZvAVoyfDylesdCv28yXQTFUOlfyZrUi2THstmU9wF8CmTXJsT0PO1+1WdwTARg24oJ2G9pPKMF8pr/E57BEzYGZIkgqsu81nVAN++weOreGCv5JwDFpSuVf+OVwi0/9ezdmjeL6C/mCicqY7x5zY6AfMAIvwruA6CBVGDVVH03fgowhcL7yGA1b5EkcwIgzOzJTVWZc6zNoE04xNlGfFB5HAaXfGwImFXj8uVTrzNgy4+y5T9XZKHaQOfHSrVBPIp9irrueLGgAAAAEABVguNTA5AAACzTCCAskwggGxoAMCAQICBFpX0aUwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UEAxMKVGhvbWFzIExpbjAeFw0xOTA3MTAwMzA4MTFaFw00NDA3MDMwMzA4MTFaMBUxEzARBgNVBAMTClRob21hcyBMaW4wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCK6YYBJW5XkcSjOw4Pe3PvR7SBNhwk7EMOn7m7vaWP8WLf4l1ozuNqm8+OOt3YoVGaOicERjupyMaA4AMYgXnPJCgoS+Q6tfuwAoQgXeHjTlA9PHag7Lbn7es98Mg8ZJIVYjgUYV81KzOrjL7GTVSoxYUfZhBuPlKldLT6kgJU8S5K+DNRPHv9C5XD9t/od2idQddBPIjzoEoBEv70/fZ+XBiFBoY1z/2BGRw8Y4gJTaPsxXliXW8isjv9iJbplgdIXtpoFJPxee3uC/3+Eshud1uOsnli/vvDSL0a2bA24bt1SY6On8BnJ2slSpgksj9s6vbNber1mVIK9kb7XTEFAgMBAAGjITAfMB0GA1UdDgQWBBS3kmY2XBgQbNpXiFPA6W2pMKHNNjANBgkqhkiG9w0BAQsFAAOCAQEAc5GQuHKQYMzZqP2zXx9cYMcLUYJj9AyZ3z52viI2TXWYY4b8mfZtKqJBTLDUnt2WFXe9N8r/qjNZqKpfgYrxd3XWUgTbwRs/V5vO/wgV2BiwgwjsecHL2CHXzc+dauAlwAPcPkuZoCEFQYKdbHj7gv4t88R0n/eLRkVlJr/fTDip+eBC4q2IFVz+HZ4o7UOnJP2h1h99kZUbP4781kml6tGYIz5GSDYXmDkvGrBhF+3v+C2fcHXLtESI9dwShBi6nFHGsiee4FgzIRjfX7on/FWazfBdno+xT6VFFYzq0HRQ85fLVm3G3ibBG88o1x3cPV9geGzqcAOiobYOgakmo1pa3S84oFTUgf3TdSrhXoLqcaf0"
      ANDROID_KEYSTORE_ALIAS: "thomas-lin"
      EXPO_ANDROID_KEYSTORE_PASSWORD: 2j03z83
      EXPO_ANDROID_KEY_PASSWORD: 2j03z83
      PUBLIC_URL: http://10.1.120.10:3000/thomas/ota-hello-expo/raw/master/android-index.json
    commands:
      # - apk update && apk add --no-cache openjdk8
      - yarn global add gulp-cli turtle-cli@$TURTLE_VERSION
      # - export PATH=$(yarn global dir):$PATH
      # - echo $PATH
      # - turtle --version
      - turtle
      # - turtle setup:android
      # - echo $ANDROID_KEYSTORE_BASE64 > keystore.jks.base64
      # - base64 --decode keystore.jks.base64 > keystore.jks
      # - turtle build:android --public-url $PUBLIC_URL -t apk --keystore-path ./keystore.jks --keystore-alias $ANDROID_KEYSTORE_ALIAS -o ./$DRONE_REPO_NAME-$DRONE_COMMIT.apk
      # - cp ./$DRONE_REPO_NAME-$DRONE_COMMIT.apk /tmp

  # - name: deploy
  #   image: docker:git
  #   volumes:
  #     - name: output
  #       path: /tmp
  #   environment:
  #     OTA_HOST: 10.1.120.10:3000
  #     OTA_ACCOUNT: thomas
  #     OTA_TOKEN: c3bf9b25e7d2fc44076535e9642819c0bf3d3ade
  #     OTA_REPO: thomas/ota-hello-expo
  #     USER_NAME: "Thomas Lin"
  #     USER_EMALI: thomas@hello.expo
  #   commands:
  #     - git config --global user.email "$USER_EMAIL"
  #     - git config --global user.name "$USER_NAME"
  #     - git init temp && cd temp
  #     - git remote add origin http://$OTA_ACCOUNT:$OTA_TOKEN@$OTA_HOST/$OTA_REPO
  #     - git pull --rebase origin master
  #     - mkdir -p output
  #     - cp /tmp/* ./output
  #     - git add * && git commit -m "deploy app"
  #     - git push origin master

volumes:
# - name: exported
#   host:
#     path: /tmp/hello-expo-exported
  - name: dist
    temp: {}
  - name: output
    temp: {}