kind: pipeline
name: build standalone app

steps:
  - name: build
    image: node:10.16.0-stretch
    volumes:
      - name: cache
        path: /tmp
    commands:
      # - yarn
      # - yarn global add expo-cli
      # - expo optimize
      # - expo export -p http://10.1.120.10:3000/thomas/ota-hello-expo/raw/master
      # - cp -r dist /tmp
      - cp package.json /tmp

  - name: publish to ota by token
    image: docker:git
    volumes:
      - name: cache
        path: /tmp
    environment:
      TOKEN: c3bf9b25e7d2fc44076535e9642819c0bf3d3ade
    commands:
      # - env
      - git config --global user.email "thomas@hello.expo"
      - git config --global user.name "Thomas"
      - git init temp && cd temp
      - git remote add origin http://thomas:$TOKEN@10.1.120.10:3000/thomas/ota-hello-expo
      - git pull --rebase
      # - git pull origin master && git checkout master
      - cp /tmp/package.json ./
      - git add * && git commit -m "publish ota"
      - git push origin master
  # - name: export app
  #   image: bycedric/expo-cli
  #   volumes:
  #   - name: cache
  #     path: /tmp/hello-expo-exported
  #   commands:
  #     - --version
  #     - optimize
  #     - export -p http://abc.123 --output-dir /tmp/hello-expo-exported

volumes:
# - name: exported
#   host:
#     path: /tmp/hello-expo-exported
- name: cache
  temp: {}