kind: pipeline
name: build standalone app

steps:
- name: export app
  image: bycedric/expo-cli
  volumes:
  - name: cache
    path: /tmp/hello-expo-exported
  command:
  - yarn
  - expo export -p http://abc.123 --output-dir /tmp/hello-expo-exported
  # - yarn global --help
  # - yarn global dir
  # - expo export -p http://abc.123 --output-dir /tmp/hello-expo-exported

volumes:
# - name: exported
#   host:
#     path: /tmp/hello-expo-exported
- name: cache
  temp: {}