kind: pipeline
name: build standalone app

steps:
- name: export app
  image: node:10.16.0-stretch
  volumes:
  - name: cache
    path: /tmp/hello-expo-exported
  command:
  - export PATH="/usr/local/bin/yarn:$PATH"
  # - npm install -g yarn expo-cli
  - "yarn --version"
  # - yarn global --help
  # - yarn global dir
  # - expo export -p http://abc.123 --output-dir /tmp/hello-expo-exported

volumes:
# - name: exported
#   host:
#     path: /tmp/hello-expo-exported
- name: cache
  temp: {}