kind: pipeline
name: build standalone app

steps:
  # - name: build
  #   image: node:10.16.0-stretch
  #   volumes:
  #     - name: cache
  #       path: /tmp
  #   commands:
  #     - yarn
  #     - yarn global add expo-cli
  #     - expo optimize
  #     - expo export -p http://10.1.120.10:3000/thomas/ota-hello-expo/raw/master
  #     - cp -r dist /tmp

  - name: publish to ota by token
    image: docker:git
    volumes:
      - name: cache
        path: /tmp/test
    environment:
      TOKEN:
        from_secret: giteaOTAToken
      USERNAME:
        from_secret: username
    commands:
      # - env
      - echo $GITEAOTATOKEN
      - echo $${TOKEN}
      - git config --global user.email "thomas@hello.expo"
      - git config --global user.name "Thomas"
      - cp package.json /tmp/test
      - cd /tmp/test
      - git init
      - git remote add origin http://thomas:$TOKEN@10.1.120.10:3000/thomas/ota-hello-expo
      - git config --list
      - git add *
      - git commit -m "update"
      - git push origin master
  # - name: export app
  #   image: bycedric/expo-cli
  #   volumes:
  #   - name: cache
  #     path: /tmp/hello-expo-exported
  #   commands:
  #     - --version
  #     - optimize
  #     - export -p http://abc.123 --output-dir /tmp/hello-expo-exported

volumes:
# - name: exported
#   host:
#     path: /tmp/hello-expo-exported
- name: cache
  temp: {}